### ISSUE TITLE
Just A Question

### ISSUE THREAD

**Issue by ericnyamubbp** [Zarcolio/ZecList#1]
Hi

How did you get all those login urls?It would be nice if you made another updated list of them

Thanks

**Comment by Zarcolio** [comment]
Hi,

Thx for your interest!
You're talking about the 1.3M list?
I didn't generate it myself but I downloaded it somewhere... But too long ago to remember where 😅

**Comment by Zarcolio** [comment]
Have you tried any of my scripts?
